version: '3.0'

services:

    web:
        build: .
        restart: always
        container_name: python-flask
        ports:
            - 3500:3500


    db:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: database
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: qmate


    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 8080:8080
    
